### ISSUE TITLE
 Journal Article

### ISSUE THREAD

**Issue by vincenttlzs** [mo42/ler#1]
Hi, I want to appreciate you for this repository, 
and I am wondering if this algorithm published in any journal article? 
Thank you for your time, and looking forward to hearing back from you.
That would be great to email me if you like. 
My email: lzs_vincent@foxmail.com

**Comment by mo42** [comment]
Hi vincenttlzs,
this work was part of my bachelor thesis. I'll send you more information via email.
Best,
Moritz
